### ISSUE TITLE
Search issues: ODD behaviours in search results

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#63]
The list of search results doesn't use the ODD processing, and so all of the behaviours defined by the ODD (like brackets around unclear or supplied text, or replacing `<ptr>` elements with the `<title>` of the corresponding record) are not used. The result is that the search results don't look as one would expect them to look (try searching "Based on" in "Commentary": since this is always followed by a `<ptr>` element, it is always blank in the search results).

Is there a way to process the KWIC results with the ODD? (I imagine that this is non-trivial.) Otherwise we can think of other solutions (like writings special xquery transforms for the KWIC results).

**Comment by wsalesky** [comment]
@aso2101 This seems to do the trick without any noticeable of a performance hit. If it works as you expected, you may close the ticket. 

See pull request: https://github.com/aso2101/satavahana-inscriptions/pull/71

**Comment by aso2101** [comment]
After merging, I noticed that the following error occurs when I search for text (using chimu* as a test):

```
err:XPTY0004 expression to the left of a lookup operator needs to be a sequence of maps or arrays [at line 546, column 94, source: /db/apps/SAI/modules/app.xql] In function: (node()*, map?, xs:string?) [10:54:/db/apps/SAI/modules/pm-config.xql] app:show-hits(node()*, map, xs:integer, xs:integer) [221:18:/db/apps/SAI/modules/app.xql] templates:call-with-args(function, function*, element(), map) [208:13:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*, element()) [205:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call-by-introspection(element(), map, map, function) [187:28:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call(item(), element(), map) [135:36:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [280:13:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*) [273:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*, element()) [205:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call-by-introspection(element(), map, map, function) [187:28:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call(item(), element(), map) [135:36:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [146:81:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [33:13:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] intl:translate(node(), map, xs:string?, xs:string?) [221:18:/db/apps/SAI/modules/lib/i18n-templates.xql] templates:call-with-args(function, function*, element(), map) [208:13:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*, element()) [205:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call-by-introspection(element(), map, map, function) [187:28:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call(item(), element(), map) [135:36:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [527:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] pages:app-root(node(), map) [217:18:/db/apps/SAI/modules/lib/pages.xql] templates:call-with-args(function, function*, element(), map) [208:13:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*, element()) [205:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call-by-introspection(element(), map, map, function) [187:28:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call(item(), element(), map) [135:36:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [465:17:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*) [273:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process-output(element(), map, item()*, element()) [205:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call-by-introspection(element(), map, map, function) [187:28:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:call(item(), element(), map) [135:36:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [131:51:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:process(node()*, map) [88:9:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql] templates:apply(node()+, function, map?, map?) [49:5:/home/andrew/applications/eXistDB3/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
```

**Comment by wsalesky** [comment]
Is this now on the master branch? I suspect a merge issue, and want to make sure I change it in the correct place. (I don't get the error on my local install, running the master branch. )

**Comment by wsalesky** [comment]
This should fix the issue.

**Comment by aso2101** [comment]
ī am still getting the same error, with an indication that the problem is on [line 512 of app.xql](https://github.com/aso2101/satavahana-inscriptions/blob/7100066ef335bebb9610fe77aafe576261374172/modules/app.xql#L512). Are the results appearing on your version?

**Comment by wsalesky** [comment]
Yes, this is what I am getting (see screen shot).
I will do some investigating

**Comment by wsalesky** [comment]
Did you rebuild and deploy the branch? Or just upload the updated code?
-Winona

**Comment by wsalesky** [comment]
Any luck?

**Comment by aso2101** [comment]
this is strange, because after rebuilding and deploying, i get the same issue. i wonder if it has to do with something in the data repository that is causing the app to fail to generate the right model for the hit. but i can't find any other evidence of a problem. what version of the data repository are you using? (also: your screenshot didn't come through.)

**Comment by wsalesky** [comment]
Can you try the new branch? (https://github.com/aso2101/satavahana-inscriptions/tree/issue63-alt)
This works on my local install with a full rebuild of both data and application. However there are some quirks. For example, although a search returns a result if the element is suppressed by the ODD nothing will show up in the result. A good example is any search in the metadata. 
example: 
http://localhost:8080/exist/apps/SAI/search.html?query=gateway&filter=iMetadata

There are also instances where you get duplicated results, I assume the information is output twice in the HTML? 
example: 
http://localhost:8080/exist/apps/SAI/search.html?query=chimu*&filter=iText
